import React from 'react';

interface ImageDisplayProps {
  isLoading: boolean;
  error: string | null;
  imageUrl: string | null;
}

const LoadingSpinner: React.FC = () => (
  <div className="flex flex-col items-center justify-center text-slate-400">
    <svg className="animate-spin h-10 w-10 text-indigo-400 mb-3" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
    </svg>
    <p className="text-lg font-medium">AI is thinking...</p>
    <p className="text-sm">This can take a moment.</p>
  </div>
);

const ErrorAlert: React.FC<{ message: string }> = ({ message }) => (
  <div className="bg-red-900/50 border border-red-700 text-red-300 px-4 py-3 rounded-lg relative w-full max-w-md" role="alert">
    <strong className="font-bold">Error!</strong>
    <span className="block sm:inline ml-2">{message}</span>
  </div>
);

const ImageIcon: React.FC<React.SVGProps<SVGSVGElement>> = (props) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
        <rect width="18" height="18" x="3" y="3" rx="2" ry="2"/>
        <circle cx="9" cy="9" r="2"/>
        <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"/>
    </svg>
);


export const ImageDisplay: React.FC<ImageDisplayProps> = ({ isLoading, error, imageUrl }) => {
  if (isLoading) {
    return <LoadingSpinner />;
  }

  if (error) {
    return <ErrorAlert message={error} />;
  }

  if (imageUrl) {
    return (
      <img
        src={imageUrl}
        alt="Generated by AI"
        className="max-w-full max-h-full object-contain rounded-lg shadow-2xl"
      />
    );
  }

  return (
    <div className="flex flex-col items-center justify-center text-slate-500 text-center p-8">
        <ImageIcon className="h-16 w-16 text-slate-600 mb-4" />
      <h3 className="text-lg font-medium text-slate-400">Your masterpiece awaits</h3>
      <p className="max-w-xs">Your generated or edited image will appear here. Get started on the left!</p>
    </div>
  );
};
